language: ruby
rvm:
- 2.2
script: jekyll build
branches:
  only:
  - travis
after_success:
    cd ./_site && find -type f -exec curl -u $FTP_USER_NEW:$FTP_PASS_NEW --ftp-create-dirs -T {} ftp://brandonz.me;