language: ruby
rvm:
- 2.2
script: jekyll build
branches:
  only:
  - travis
after_success:
    cd ./_site && find -type f -exec curl -u $FTP_USER_OLD:$FTP_PASS_OLD --ftp-create-dirs -T {} ftp://brandonious.com{} \;